### ISSUE TITLE
Import the project's rating popularity

### ISSUE THREAD

**Issue by BrunoVernay** [BrunoVernay/tw-tools-update#1]

**Comment by tbabej** [comment]
As an alternative sort option, the timestamp of the last update of the repository could be used.

**Comment by BrunoVernay** [comment]
I used the https://developer.github.com/v3/activity/starring/ 
As long as the numbers are below 1.000 stars, the process should be OK.
(I start a new issue to sort by last updates)

**Comment by BrunoVernay** [comment]
Next step is to use it in the web site
https://github.com/BrunoVernay/taskwarrior-site-test/issues/7
https://github.com/BrunoVernay/taskwarrior-site-test/issues/8
